application: bn-devtest
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /get_nearby_venues
  script: get_nearby_venues.py

- url: .* 
  script: index.py
